language: perl
install: 
  - export LDLOADLIBS=-lstdc++ 
  - export BOOST_DIR=$HOME/boost_1_58_0 
  - wget https://sourceforge.net/projects/boost/files/boost/1.58.0/boost_1_58_0.tar.bz2
  - tar -xf boost_1_58_0.tar.bz2
  - cd $HOME/boost_1_58_0
  - ./bootstrap.sh gcc
  - ./b2 
script: perl ./Build.PL
perl:
  - "5.14"
  - "5.18"
  - "5.20"
branches:
  only:
    - master
    - stable
sudo: false
cache:
    directories:
    - $HOME/boost_1_58_0
