language: perl
install: 
  - export LDLOADLIBS=-lstdc++ 
  - export BOOST_DIR=$HOME/boost_1_58_0 
  - export BUILD_DIR=$(pwd)
  - if [ -d $HOME/boost_1_58_0 ]; then wget https://sourceforge.net/projects/boost/files/boost/1.58.0/boost_1_58_0.tar.bz2; fi
  - if [ -d $HOME/boost_1_58_0 ]; then tar -xf boost_1_58_0.tar.bz2; fi
  - if [ -d $HOME/boost_1_58_0 ]; then mv boost_1_58_0 $HOME; fi
  - if [ -d $HOME/boost_1_58_0 ]; then cd $HOME/boost_1_58_0; fi
  - if [ -d $HOME/boost_1_58_0 ]; then $HOME/boost_1_58_0/bootstrap.sh gcc; fi
  - if [ -d $HOME/boost_1_58_0 ]; then $HOME/boost_1_58_0/b2; fi
  - cd $BUILD_DIR
script: perl ./Build.PL
perl:
  - "5.14"
  - "5.18"
  - "5.20"
branches:
  only:
    - master
    - stable
sudo: false
cache:
    directories:
    - $HOME/boost_1_58_0
